version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=poojasrinivasan
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=customer_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U poojasrinivasan -d customer_db"]
      interval: 5s
      timeout: 5s
      retries: 10

#  customerservice:   # âœ… renamed from inventoryservice
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: customerservice
#    depends_on:
#      postgres:
#        condition: service_healthy
##    ports:
#      - "3000:3000"
#    volumes:
#      - ./config:/app/config
#    environment:
#      - APP_NAME=customerservice
#      - DB_HOST=postgres
#      - DB_USER=poojasrinivasan
#      - DB_PASSWORD=password
#      - DB_NAME=customer_db
#      - DB_PORT=5432
#    restart: on-failure
#
#volumes:
#  postgres_data: